create table tb_frete (frete_id int8 generated by default as identity, cep_destino varchar(255), cep_origem varchar(255), data_consulta timestamp, data_prevista_entrega timestamp, nome_destinatario varchar(255), vl_total_frete float8, primary key (frete_id));
INSERT INTO tb_frete(CEP_DESTINO, CEP_ORIGEM, NOME_DESTINATARIO, VL_TOTAL_FRETE) VALUES ('88060230', '88060231', 'João Victor', 500.0);
